#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : vpnc
Version  : 101208be5b74039ea70b9e007ce0d6c9fbe44d82
Release  : 1
URL      : https://github.com/streambinder/vpnc/archive/101208be5b74039ea70b9e007ce0d6c9fbe44d82.tar.gz
Source0  : https://github.com/streambinder/vpnc/archive/101208be5b74039ea70b9e007ce0d6c9fbe44d82.tar.gz
Summary  : VPN client for cisco3000 VPN Concentrators
Group    : Development/Tools
License  : GPL-3.0
Requires: vpnc-license = %{version}-%{release}
BuildRequires : gnutls-dev
BuildRequires : libgcrypt-dev
BuildRequires : libgpg-error-dev
BuildRequires : pkgconfig(gnutls)

%description
# VPNC
## What is it
VPNC is a VPN client compatible with Cisco's EasyVPN equipment. It supports IPSec (ESP) with Mode Configuration and Xauth. Supports only shared-secret IPSec authentication with Xauth, AES (256, 192, 128), 3DES, 1DES, MD5, SHA1, DH1/2/5 and IP tunneling. It runs entirely in userspace. Only "Universal TUN/TAP device driver support" is needed in kernel.

%package license
Summary: license components for the vpnc package.
Group: Default

%description license
license components for the vpnc package.


%prep
%setup -q -n vpnc-101208be5b74039ea70b9e007ce0d6c9fbe44d82

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1558567678
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1558567678
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/vpnc
cp LICENSE %{buildroot}/usr/share/package-licenses/vpnc/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/vpnc/LICENSE
